"""Tests for the auto-generated pydantic models."""

from __future__ import annotations

import inspect
import json
import warnings
from enum import Enum
from pathlib import Path
from typing import Any, get_args

from pydantic import BaseModel

from decidalo_client import models as dm

SPEC_PATH = Path(__file__).parent.parent / "openapi" / "v1" / "swagger.json"

GENERATED_CLASSES = [
    obj
    for _, obj in inspect.getmembers(dm, inspect.isclass)
    if obj.__module__ == "decidalo_client.models._autogenerated"
]
GENERATED_MODELS = [obj for obj in GENERATED_CLASSES if issubclass(obj, BaseModel)]


class TestModelsMatchSpec:
    """Tests that the generated models are in sync with the OpenAPI spec in the repository."""

    def test_every_schema_has_a_model_and_vice_versa(self) -> None:
        """Test that the models were regenerated after the last spec update (see the README)."""
        spec: dict[str, Any] = json.loads(SPEC_PATH.read_text(encoding="utf-8"))

        assert {cls.__name__ for cls in GENERATED_CLASSES} == set(spec["components"]["schemas"])


class TestExtraFields:
    """Tests for the handling of fields that are unknown to the OpenAPI spec."""

    def test_generated_models_are_collected(self) -> None:
        """Test that the model collection used by the other tests is not empty."""
        assert len(GENERATED_MODELS) > 100

    def test_no_model_forbids_extra_fields(self) -> None:
        """Test that no generated model rejects unknown fields.

        The decidalo API adds response fields regularly. Models generated with
        extra="forbid" fail to parse such responses, so the models must be
        generated with --extra-fields ignore (see the README).
        """
        forbidding = [model.__name__ for model in GENERATED_MODELS if model.model_config.get("extra") == "forbid"]

        assert forbidding == []

    def test_unknown_response_field_is_ignored(self) -> None:
        """Test that a response containing a field unknown to the spec is parsed and the field dropped."""
        user = dm.UserOverview.model_validate(
            {
                "userID": 1,
                "email": "john.doe@example.com",
                "displayName": "John Doe",
                "employeeTypeID": 1,
                "employeeTypeName": "Employee",
                "includeInResourceManagement": True,
                "hasLogin": True,
                "creationDate": "2024-01-01T00:00:00Z",
                "lastEditDate": "2024-01-15T00:00:00Z",
                "fieldFromTheFuture": 42,
            }
        )

        assert user.userID == 1
        assert "fieldFromTheFuture" not in user.model_dump()


class TestEnumDefaults:
    """Tests for the defaults of enum-typed fields."""

    def test_no_enum_field_defaults_to_a_plain_string(self) -> None:
        """Test that enum defaults are enum members (models must be generated with --set-default-enum-member)."""
        offenders = [
            f"{model.__name__}.{name}"
            for model in GENERATED_MODELS
            for name, field in model.model_fields.items()
            if isinstance(field.default, str)
            and not isinstance(field.default, Enum)
            and any(isinstance(arg, type) and issubclass(arg, Enum) for arg in get_args(field.annotation))
        ]

        assert offenders == []

    def test_serializing_an_enum_default_emits_no_warning(self) -> None:
        """Test that a model relying on an enum default serializes without a pydantic serializer warning."""
        entry = dm.RecordingEntryImportItem(userID=1)

        with warnings.catch_warnings():
            warnings.simplefilter("error")
            dumped = entry.model_dump_json(exclude_none=True)

        assert dumped == '{"userID":1,"status":"Open"}'


class TestApiBreakingChanges:
    """Tests documenting the breaking changes of the import API that surface in the models."""

    def test_time_recording_entry_status_values(self) -> None:
        """Test that the status "Draft" was replaced by "Open" and the cancellation states were added."""
        assert [status.value for status in dm.TimeRecordingEntryStatus] == [
            "Suggested",
            "Open",
            "Submitted",
            "Confirmed",
            "Cancelled",
            "CancellationSubmitted",
        ]

    def test_recording_entry_status_defaults_to_open(self) -> None:
        """Test that a new recording entry defaults to the status "Open"."""
        assert dm.RecordingEntryImportItem().status == dm.TimeRecordingEntryStatus.Open

    def test_order_references_projects_as_list(self) -> None:
        """Test that an order references its projects via 'projects' instead of projectCode/projectReferenceID."""
        order = dm.OrderImportItem(
            code="ORDER-1",
            projects=[
                dm.OrderProjectImportItem(projectCode="PROJ001"),
                dm.OrderProjectImportItem(projectReferenceID=7),
            ],
        )

        assert order.model_dump(exclude_none=True) == {
            "code": "ORDER-1",
            "projects": [{"projectCode": "PROJ001"}, {"projectReferenceID": 7}],
        }
        assert "projectCode" not in dm.OrderImportItem.model_fields
        assert "projectReferenceID" not in dm.OrderImportOutput.model_fields

    def test_project_classifications_are_select_options(self) -> None:
        """Test that business unit, status & co. of a project are select options (id and/or value)."""
        properties = dm.ProjectReferencePropertiesInput(
            businessUnit=dm.SelectOptionFieldInput(id=3),
            projectStatus=dm.SelectOptionFieldInput(value="Active"),
        )

        dumped = properties.model_dump(exclude_none=True)
        assert dumped["businessUnit"] == {"id": 3}
        assert dumped["projectStatus"] == {"value": "Active"}
