"""Tests for the auto-generated pydantic models."""

from __future__ import annotations

import inspect

from pydantic import BaseModel

from decidalo_client import models as dm

GENERATED_MODELS = [
    obj
    for _, obj in inspect.getmembers(dm, inspect.isclass)
    if issubclass(obj, BaseModel) and obj.__module__ == "decidalo_client.models._autogenerated"
]


class TestExtraFields:
    """Tests for the handling of fields that are unknown to the OpenAPI spec."""

    def test_generated_models_are_collected(self) -> None:
        """Test that the model collection used by the other tests is not empty."""
        assert len(GENERATED_MODELS) > 100

    def test_no_model_forbids_extra_fields(self) -> None:
        """Test that no generated model rejects unknown fields.

        The decidalo API adds response fields regularly. Models generated with
        extra="forbid" fail to parse such responses, so the models must be
        generated with --extra-fields ignore (see the README).
        """
        forbidding = [model.__name__ for model in GENERATED_MODELS if model.model_config.get("extra") == "forbid"]

        assert forbidding == []

    def test_unknown_response_field_is_ignored(self) -> None:
        """Test that a response containing a field unknown to the spec is parsed and the field dropped."""
        user = dm.UserOverview.model_validate(
            {
                "userID": 1,
                "email": "john.doe@example.com",
                "displayName": "John Doe",
                "employeeTypeID": 1,
                "employeeTypeName": "Employee",
                "includeInResourceManagement": True,
                "hasLogin": True,
                "creationDate": "2024-01-01T00:00:00Z",
                "lastEditDate": "2024-01-15T00:00:00Z",
                "fieldFromTheFuture": 42,
            }
        )

        assert user.userID == 1
        assert "fieldFromTheFuture" not in user.model_dump()
